project_name: siren

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - make clean

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"

builds:
  - id: siren
    main: ./main.go
    binary: siren
    flags: [-a]
    ldflags:
      - -X github.com/raystack/siren/cli.Version={{.Tag}}
      - -X github.com/raystack/siren/cli.BuildCommit={{.FullCommit}}
      - -X github.com/raystack/siren/cli.BuildDate={{.Date}}
    goos: [linux, darwin, windows]
    goarch: [amd64, 386, arm, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - id: "archives"
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - id: dockerhub
    image_templates:
      - "docker.io/raystack/{{.ProjectName}}:latest"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Tag }}-amd64"

nfpms:
  - maintainer: Raystack
    description: Universal data observability tool.
    homepage: https://github.com/raystack/siren
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk

scoops:
  - homepage: "https://github.com/raystack/siren"
    description: "Universal data observability tool."
    license: Apache 2.0
    bucket:
      owner: raystack
      name: scoop-bucket

brews:
  - name: siren
    homepage: "https://github.com/raystack/siren"
    description: "Universal data observability tool."
    tap:
      owner: raystack
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "siren"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com
