project_name: siren

release:
  draft: true
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - main: ./main.go
    id: "siren"
    binary: siren
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/odpf/siren/config.Version={{.Tag}} -X github.com/odpf/siren/config.BuildCommit={{.FullCommit}} -X github.com/odpf/siren/config.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux, windows]
    goarch: [amd64, 386]

archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "Merge pull request"
      - "Merge branch"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - siren
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/odpf/{{.ProjectName}}:latest"
      - "docker.io/odpf/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/odpf/{{.ProjectName}}:{{ .Tag }}-amd64"

brews:
  - name: siren
    homepage: "https://github.com/odpf/siren"
    description: "Universal data observability tool."
    tap:
      owner: odpf
      name: homebrew-taps
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "siren"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com
