version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "siren_postgres"
    ports:
      - "5432:5432"
    volumes:
      - siren_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  siren_dbdata:
