receivers:
  opencensus:

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: "http://localhost:9000/api/v1/push"
    tls:
      insecure: true
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": "NEW_RELIC_API_KEY"
  prometheusremotewrite:
    endpoint: http://host.docker.internal:9009/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: odpf
    external_labels:
      service: siren
      team: odpf-infra
      environment: development
      host: local
  logging:
    loglevel: debug

extensions:
  health_check:

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: debug
      initial_fields:
        service: my-instance
  pipelines:
    traces:
      receivers: [opencensus]
      processors: [batch]
      exporters: [otlp, logging]
    metrics:
      receivers: [opencensus]
      processors: [batch]
      exporters: [prometheusremotewrite,otlp, logging]