receivers:
  statsd:
    endpoint: :8125
    aggregation_interval: 60s
    enable_metric_type: true
    is_monotonic_counter: false
    timer_histogram_mapping:
    - statsd_type: "histogram"
      observer_type: "summary"
    - statsd_type: "timing"
      observer_type: "summary"
  jaeger:
    protocols:
      grpc:
        endpoint: :14250
      thrift_http:
        endpoint: :14268
      thrift_compact:
        endpoint: :6831
  opencensus:
    endpoint: :55678
  otlp:
    protocols:
      grpc:
        endpoint: :4317
      http:
        endpoint: :4318
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: opentelemetry-collector
  #         scrape_interval: 10s
  #         static_configs:
  #           - targets:
  #               - 127.0.0.1:8888
  zipkin:
    endpoint: :9411

exporters:
  logging:
    loglevel: warn
    sampling_initial: 2
    sampling_thereafter: 500
  logging/noop:
    loglevel: info
    sampling_initial: 0
    sampling_thereafter: 0
  # otlp:
  #   endpoint: "https://otlp.nr-data.net:443"
  #   headers:
  #     api-key: xxxxxxxxxx
  prometheusremotewrite:
    endpoint: http://host.docker.internal:9009/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: gotocompany-ns
    external_labels:
      service: siren
      team: gotocompany-infra
      environment: development
      host: local
    remote_write_queue:
      enabled: true
      queue_size: 5000
      num_consumers: 2

extensions:
  health_check: {}
  memory_ballast: {}

processors:
  batch: {}
  # If set to null, will be overridden with values based on k8s resource limits
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions:
    - health_check
    - memory_ballast
  pipelines:
    logs:
      exporters:
        - logging
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
    metrics:
      exporters:
        # - logging
        - prometheusremotewrite
      processors:
        - memory_limiter
        - batch
      receivers:
        - statsd
        - otlp
        - opencensus
        # - prometheus
    traces:
      exporters: 
        - logging/noop
        # - otlp
      processors: []
        # - memory_limiter
        # - batch
      receivers:
        - otlp
        # - jaeger
        # - zipkin
        # - opencensus