# ODPF Siren Configuration
#
#
# !!WARNING!!
# This configuration file is for documentation purposes only. Do not use it in production.
#
# Siren can be configured using a configuration file and passing the file location using `--config path/to/config.yaml`.
# Per default, Siren will look up and load file ~/config.yaml. All configuration keys can be set using environment
# variables as well.
#
db:
  host: localhost
  user: postgres
  name: siren_dev
  password: ""
  port: 5432
  sslmode: disable
cortex:
  address: http://localhost:9009
newrelic:
  enabled: false
  appname: siren
  license: ____LICENSE_STRING_OF_40_CHARACTERS_____
service:
  host: localhost
  port: 8080
slack_app:
  client_id: 123.456
  client_secret: xyz
encryption_key:  ____STRING_OF_32_CHARACTERS_____
