// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/goto/siren/core/notification"
	mock "github.com/stretchr/testify/mock"
)

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

type Dispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *Dispatcher) EXPECT() *Dispatcher_Expecter {
	return &Dispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: ctx, ns
func (_m *Dispatcher) Dispatch(ctx context.Context, ns []notification.Notification) ([]string, error) {
	ret := _m.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []notification.Notification) ([]string, error)); ok {
		return rf(ctx, ns)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []notification.Notification) []string); ok {
		r0 = rf(ctx, ns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []notification.Notification) error); ok {
		r1 = rf(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Dispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type Dispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ns []notification.Notification
func (_e *Dispatcher_Expecter) Dispatch(ctx interface{}, ns interface{}) *Dispatcher_Dispatch_Call {
	return &Dispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, ns)}
}

func (_c *Dispatcher_Dispatch_Call) Run(run func(ctx context.Context, ns []notification.Notification)) *Dispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]notification.Notification))
	})
	return _c
}

func (_c *Dispatcher_Dispatch_Call) Return(_a0 []string, _a1 error) *Dispatcher_Dispatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Dispatcher_Dispatch_Call) RunAndReturn(run func(context.Context, []notification.Notification) ([]string, error)) *Dispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewDispatcher creates a new instance of Dispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dispatcher {
	mock := &Dispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
