// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	subscriptionreceiver "github.com/goto/siren/core/subscriptionreceiver"
)

// SubscriptionReceiverService is an autogenerated mock type for the SubscriptionReceiverService type
type SubscriptionReceiverService struct {
	mock.Mock
}

type SubscriptionReceiverService_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionReceiverService) EXPECT() *SubscriptionReceiverService_Expecter {
	return &SubscriptionReceiverService_Expecter{mock: &_m.Mock}
}

// BulkCreate provides a mock function with given fields: _a0, _a1
func (_m *SubscriptionReceiverService) BulkCreate(_a0 context.Context, _a1 []subscriptionreceiver.Relation) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []subscriptionreceiver.Relation) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionReceiverService_BulkCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreate'
type SubscriptionReceiverService_BulkCreate_Call struct {
	*mock.Call
}

// BulkCreate is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []subscriptionreceiver.Relation
func (_e *SubscriptionReceiverService_Expecter) BulkCreate(_a0 interface{}, _a1 interface{}) *SubscriptionReceiverService_BulkCreate_Call {
	return &SubscriptionReceiverService_BulkCreate_Call{Call: _e.mock.On("BulkCreate", _a0, _a1)}
}

func (_c *SubscriptionReceiverService_BulkCreate_Call) Run(run func(_a0 context.Context, _a1 []subscriptionreceiver.Relation)) *SubscriptionReceiverService_BulkCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]subscriptionreceiver.Relation))
	})
	return _c
}

func (_c *SubscriptionReceiverService_BulkCreate_Call) Return(_a0 error) *SubscriptionReceiverService_BulkCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionReceiverService_BulkCreate_Call) RunAndReturn(run func(context.Context, []subscriptionreceiver.Relation) error) *SubscriptionReceiverService_BulkCreate_Call {
	_c.Call.Return(run)
	return _c
}

// BulkDelete provides a mock function with given fields: _a0, _a1
func (_m *SubscriptionReceiverService) BulkDelete(_a0 context.Context, _a1 subscriptionreceiver.DeleteFilter) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, subscriptionreceiver.DeleteFilter) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionReceiverService_BulkDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDelete'
type SubscriptionReceiverService_BulkDelete_Call struct {
	*mock.Call
}

// BulkDelete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 subscriptionreceiver.DeleteFilter
func (_e *SubscriptionReceiverService_Expecter) BulkDelete(_a0 interface{}, _a1 interface{}) *SubscriptionReceiverService_BulkDelete_Call {
	return &SubscriptionReceiverService_BulkDelete_Call{Call: _e.mock.On("BulkDelete", _a0, _a1)}
}

func (_c *SubscriptionReceiverService_BulkDelete_Call) Run(run func(_a0 context.Context, _a1 subscriptionreceiver.DeleteFilter)) *SubscriptionReceiverService_BulkDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(subscriptionreceiver.DeleteFilter))
	})
	return _c
}

func (_c *SubscriptionReceiverService_BulkDelete_Call) Return(_a0 error) *SubscriptionReceiverService_BulkDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionReceiverService_BulkDelete_Call) RunAndReturn(run func(context.Context, subscriptionreceiver.DeleteFilter) error) *SubscriptionReceiverService_BulkDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSoftDelete provides a mock function with given fields: _a0, _a1
func (_m *SubscriptionReceiverService) BulkSoftDelete(_a0 context.Context, _a1 subscriptionreceiver.DeleteFilter) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BulkSoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, subscriptionreceiver.DeleteFilter) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionReceiverService_BulkSoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSoftDelete'
type SubscriptionReceiverService_BulkSoftDelete_Call struct {
	*mock.Call
}

// BulkSoftDelete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 subscriptionreceiver.DeleteFilter
func (_e *SubscriptionReceiverService_Expecter) BulkSoftDelete(_a0 interface{}, _a1 interface{}) *SubscriptionReceiverService_BulkSoftDelete_Call {
	return &SubscriptionReceiverService_BulkSoftDelete_Call{Call: _e.mock.On("BulkSoftDelete", _a0, _a1)}
}

func (_c *SubscriptionReceiverService_BulkSoftDelete_Call) Run(run func(_a0 context.Context, _a1 subscriptionreceiver.DeleteFilter)) *SubscriptionReceiverService_BulkSoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(subscriptionreceiver.DeleteFilter))
	})
	return _c
}

func (_c *SubscriptionReceiverService_BulkSoftDelete_Call) Return(_a0 error) *SubscriptionReceiverService_BulkSoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionReceiverService_BulkSoftDelete_Call) RunAndReturn(run func(context.Context, subscriptionreceiver.DeleteFilter) error) *SubscriptionReceiverService_BulkSoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpsert provides a mock function with given fields: _a0, _a1
func (_m *SubscriptionReceiverService) BulkUpsert(_a0 context.Context, _a1 []subscriptionreceiver.Relation) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []subscriptionreceiver.Relation) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionReceiverService_BulkUpsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsert'
type SubscriptionReceiverService_BulkUpsert_Call struct {
	*mock.Call
}

// BulkUpsert is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []subscriptionreceiver.Relation
func (_e *SubscriptionReceiverService_Expecter) BulkUpsert(_a0 interface{}, _a1 interface{}) *SubscriptionReceiverService_BulkUpsert_Call {
	return &SubscriptionReceiverService_BulkUpsert_Call{Call: _e.mock.On("BulkUpsert", _a0, _a1)}
}

func (_c *SubscriptionReceiverService_BulkUpsert_Call) Run(run func(_a0 context.Context, _a1 []subscriptionreceiver.Relation)) *SubscriptionReceiverService_BulkUpsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]subscriptionreceiver.Relation))
	})
	return _c
}

func (_c *SubscriptionReceiverService_BulkUpsert_Call) Return(_a0 error) *SubscriptionReceiverService_BulkUpsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionReceiverService_BulkUpsert_Call) RunAndReturn(run func(context.Context, []subscriptionreceiver.Relation) error) *SubscriptionReceiverService_BulkUpsert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: _a0, _a1
func (_m *SubscriptionReceiverService) List(_a0 context.Context, _a1 subscriptionreceiver.Filter) ([]subscriptionreceiver.Relation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []subscriptionreceiver.Relation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, subscriptionreceiver.Filter) ([]subscriptionreceiver.Relation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, subscriptionreceiver.Filter) []subscriptionreceiver.Relation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]subscriptionreceiver.Relation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, subscriptionreceiver.Filter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionReceiverService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SubscriptionReceiverService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 subscriptionreceiver.Filter
func (_e *SubscriptionReceiverService_Expecter) List(_a0 interface{}, _a1 interface{}) *SubscriptionReceiverService_List_Call {
	return &SubscriptionReceiverService_List_Call{Call: _e.mock.On("List", _a0, _a1)}
}

func (_c *SubscriptionReceiverService_List_Call) Run(run func(_a0 context.Context, _a1 subscriptionreceiver.Filter)) *SubscriptionReceiverService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(subscriptionreceiver.Filter))
	})
	return _c
}

func (_c *SubscriptionReceiverService_List_Call) Return(_a0 []subscriptionreceiver.Relation, _a1 error) *SubscriptionReceiverService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionReceiverService_List_Call) RunAndReturn(run func(context.Context, subscriptionreceiver.Filter) ([]subscriptionreceiver.Relation, error)) *SubscriptionReceiverService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewSubscriptionReceiverService creates a new instance of SubscriptionReceiverService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionReceiverService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionReceiverService {
	mock := &SubscriptionReceiverService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
